config/routes.rb
CompaniesHouseScraper::Application.routes.draw do
  resources :words do
    member do
      put :flag
      put :unflag
    end
  end
  root to: "words#index"
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/word.rb
class Word < ActiveRecord::Base

  scope :domain_available, where(:domain_available => true)
  scope :domain_unchecked, where(:domain_available => nil)
  scope :domain_unavailable, where(:domain_available => false)  
  
  scope :shortlisted, where(:shortlist => true)
  scope :unchecked, where(:shortlist => nil)
  scope :rejected, where(:shortlist => false)  
  
  scope :to_consider, domain_available.
    where("(shortlist IS NULL OR shortlist = ?) AND (flag_for_purchase = ? OR flag_for_purchase is null)", true, false)
  
  scope :flagged, where(flag_for_purchase: true)
  
  validates :computer, presence: true, uniqueness: true
  validates :human, presence: true, uniqueness: true
  
  def domain
    "#{computer}.com".downcase
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  http_basic_authenticate_with :name => "Bodacious", :password => "wordpass"
  
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :ok }
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  expose(:flagged_words) { Word.flagged.order("computer") }
  expose(:words) { Word.to_consider.order("computer").page(params[:page]).per(100) }
  expose(:word) { Word.find(params[:id])}
  
  def index
  end

  def destroy
    respond_to do |format|
      format.js{
        word.update_attribute(:shortlist, false)        
      }
    end
  end
  
  def flag
    respond_to do |format|
      format.js{
        word.update_attribute(:flag_for_purchase, true)        
      }
    end
  end
  
  def unflag
    respond_to do |format|
      format.js{
        word.update_attribute(:flag_for_purchase, false)        
      }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.status %></td>
    <td><%= company.number %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Status:</b>
  <%= @company.status %>
</p>

<p>
  <b>Number:</b>
  <%= @company.number %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompaniesHouseScraper</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="content">
  <%= yield %>  
</div>


</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/_word.html.erb
<tr id="word_<%= word.id %>">
  <td><%= word.human.titleize %></td>
  <td><%= word.domain %></td>
  <td>
    <% if word.flag_for_purchase %>
      <%= link_to 'unflag', unflag_word_path(word), remote: true, method: :put %>    
    <% else %>
      <%= link_to 'flag', flag_word_path(word), remote: true, method: :put %>
    <% end %>
  </td>      
  <td><%= link_to 'remove', word, method: :delete, remote: true %></td>
</tr>

app/views/words/destroy.js.erb
$("#word_<%= word.id %>").remove();

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/flag.js.erb
var wordRow = $("#word_<%= word.id %>").clone();
$("#words #word_<%= word.id %>").remove();
$("#flagged_words").append("<%= escape_javascript(render(word)) %>");

app/views/words/index.html.erb
<h1>Short-list of potential names</h1>

<p>
  This is a list of all the single-word domains that
  are available at the moment. If you don't like a name, click <b>remove</b>.
</p>

<table id="flagged_words">

  <%= render flagged_words %>
</table>

<hr>

<table id="words">
  <%= render words %>
</table>

<%= paginate(words) %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>

app/views/words/unflag.js.erb
var wordRow = $("#word_<%= word.id %>").clone();
$("#flagged_words #word_<%= word.id %>").remove();
$("#words").append("<%= escape_javascript(render(word)) %>");